const data= [
    {
        id:"1",
        name:"a",
        ticketType:"standard"
    },
    {
        id:"2",
        name:"b",
        ticketType:"premium"
    },
    {
        id:"3",
        name:"c",
        ticketType:"standard"
    },
    {
        id:"4",
        name:"d",
        ticketType:"standard"
    },
    {
        id:"5",
        name:"e",
        ticketType:"standard"
    },
    {
        id:"6",
        name:"f",
        ticketType:"standard"
    },
    {
        id:"7",
        name:"g",
        ticketType:"standard"
    },
    {
        id:"8",
        name:"h",
        ticketType:"standard"
    },
    {
        id:"9",
        name:"i",
        ticketType:"standard"
    },
    {
        id:"10",
        name:"j",
        ticketType:"premium"
    },
    {
        id:"11",
        name:"k",
        ticketType:"standard"
    },
    {
        id:"12",
        name:"l",
        ticketType:"premium"
    },
    {
        id:"13",
        name:"m",
        ticketType:"standard"
    },
    {
        id:"14",
        name:"n",
        ticketType:"premium"
    },
    {
        id:"15",
        name:"o",
        ticketType:"standard"
    },
    {
        id:"16",
        name:"p",
        ticketType:"standard"
    },
    {
        id:"17",
        name:"q",
        ticketType:"standard"
    },
    {
        id:"18",
        name:"r",
        ticketType:"standard"
    },
    {
        id:"19",
        name:"s",
        ticketType:"standard"
    },
    {
        id:"20",
        name:"t",
        ticketType:"premium"
    },
    {
        id:"21",
        name:"u",
        ticketType:"premium"
    },
    {
        id:"22",
        name:"v",
        ticketType:"standard"
    },
    {
        id:"23",
        name:"w",
        ticketType:"standard"
    },
    {
        id:"24",
        name:"x",
        ticketType:"standard"
    },
    {
        id:"25",
        name:"y",
        ticketType:"standard"
    },
    {
        id:"26",
        name:"z",
        ticketType:"premium"
    },
    {
        id:"27",
        name:"aa",
        ticketType:"standard"
    },
    {
        id:"28",
        name:"ab",
        ticketType:"standard"
    },
    {
        id:"29",
        name:"ac",
        ticketType:"premium"
    },
    {
        id:"30",
        name:"ad",
        ticketType:"premium"
    },
    {
        id:"31",
        name:"ae",
        ticketType:"standard"
    },
    {
        id:"32",
        name:"af",
        ticketType:"premium"
    }
]

export default data;